spring:
  application:
    name: Task-Manager-Api
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager_db
    username: Userr
    password: 12345
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC
  task:
    execution:
      pool:
        core-size: 2
        max-size: 10
        queue-capacity: 100
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
    session:
      timeout: 30m
cors:
  allowed-origins: http://localhost:8080
jwt:
  secret: ${JWT_SECRET}
  expiration: 36000000
  refreshExpiration: 86400000
  prefix: Bearer
  header: Authorization
  tokenPrefix: Bearer
  userClaim: role
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.atelierAI: DEBUG
  file:
    name: logs/task-manger-backend.log
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
swagger:
  server:
    url: http://localhost:8080